services:
  - type: web
    name: bugboy-ruby
    runtime: ruby
    buildCommand: bundle install
    startCommand: bundle exec ruby app.rb -o 0.0.0.0 -p $PORT
    envVars:
      - key: RUBY_VERSION
        value: "3.3.0"
